import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import logo from '../../public/logo.svg'
import logoWhite from '../../public/logoWhite.svg'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Logo() {
  return (
    <Image
      src={logo}
      alt="Website Logo"
      style={{
        objectFit: 'contain',
      }}
    />
  )
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta httpEquiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>Guitar Roadmap</title>
      </head>

      <body>
        <nav className="flex items-center py-6 px-60 gap-10 text-xs">
          <Link href={'/'} className="max-h-6">
            {Logo()}
          </Link>
          <Link href={'/'}> Home </Link>
          <Link href={'/'}> Chord </Link>
          <Link href={'/'}> Scale </Link>
          <Link href={'/'} className="ml-auto"> Log In </Link>
        </nav>
        {children}

        <footer>

          <div className="h-44 flex flex-col justify-center items-center gap-4 py-10 text-4xl bg-wine-800 text-white">
            <Image
              src={logoWhite}
              alt="Website Logo"
              sizes="100%"
              style={{
                objectFit: 'contain',
                width: '40px'
              }}
            />
            Thanks for your support!
          </div>
          <div className="h-20 flex py-6 px-60 gap-10 text-xs bg-wine-900 text-white">
            <div className="flex flex-col">
              Full-Stack Developer
              <b>
                Hoang Quoc Dat
              </b>
            </div>

            <div className="flex flex-col">
              Full-Stack Developer
              <b>
                Nguyen Ngoc Hai
              </b>
            </div>

            <div className="flex flex-col">
              UX/UI Designer
              <b>
                Vu Le Vinh
              </b>
            </div>

          </div>
        </footer>

      </body>
    </html>
  );
}
